### NUMPY
NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
NumPy stands for Numerical Python.

In [4]:
import numpy as np

## create array using numpy
## create 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

## NumPY Methods


In [ ]:
np.ones((3,4))  ## an 2d array containing only 1 with 3 rows and 4 columns 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ATTRIBUTES OF NUMPY ARRAY


In [34]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


## NUMPY VECTORISED OPERATIONS

In [38]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr1+arr2)

## Element wise substraction
print("Substraction:",arr1-arr2)

## Element wise Multiplication
print("Multiplication:",arr1*arr2)

## Element wise Division
print("Division:",arr2/arr1)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


## Universal Functions

In [40]:
arr = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

##Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## ARRAY SLICING AND INDEXING

In [50]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:\n",arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
print(arr[0][0])
arr[0:2,2:]

1


array([[3, 4],
       [7, 8]])

In [53]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [63]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

## Modify Array Elements

In [70]:
arr = np.array([[1,2,3,4],[2,3,4,5]])
print("Array:\n",arr)
print("\n")
arr[0,0] = 100
arr[1:] = 200
print("Modified Array:\n",arr)

Array:
 [[1 2 3 4]
 [2 3 4 5]]


Modified Array:
 [[100   2   3   4]
 [200 200 200 200]]


## Practical Applications


In [74]:
## Statistical concepts

arr = np.array([1,2,3,4,5,6,7,8,9,11,15])

## MEAN
print("Mean:",np.mean(arr))

## Median
print("Median:",np.median(arr))

## Standarad deviation
print("Standarad deviation:",np.std(arr))

## Variance
print("Variance:",np.var(arr))



Mean: 6.454545454545454
Median: 6.0
Standarad deviation: 3.9626354032187945
Variance: 15.702479338842977


In [80]:
##Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

print("No. greater than 5:",data[data>5])

print("No.greater than 5 and less than 8:",data[(data>=5) & (data<=8)])

No. greater than 5: [ 6  7  8  9 10]
No.greater than 5 and less than 8: [5 6 7 8]
