## The Numpy ndarray: A Multidimensional Array Object

In [2]:
import numpy as np
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])

In [3]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

## Creating ndarrays

In [9]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

## Methods



In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### TypeCasting of array

In [37]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [38]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [39]:
float_arr.dtype

dtype('float64')

In [46]:
numeric_strings=np.array(['1.5','4.5','8.9'])
numeric_strings.dtype

dtype('<U3')

In [47]:
numeric_strings.astype(float)

array([1.5, 4.5, 8.9])