## Arthematic with Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [4]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr1 = np.array([[0,4,1],[7,2,12]])
arr1>arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing
### 1D array


In [14]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr[5])
print(arr[5:8])

6
[6 7 8]


In [18]:
arr[5:8] = 12
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12,  9])

In [20]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [21]:
arr_slice[1] = 12345
arr

array([    1,     2,     3,     4,     5,    12, 12345,    12,     9])

In [22]:
arr_slice[:] = 64
arr

array([ 1,  2,  3,  4,  5, 64, 64, 64,  9])

### 2D array

In [23]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[2]

array([7, 8, 9])

In [25]:
arr2d[0][2]

np.int64(3)